apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         
    keyvaultName: "akv-podidentities-demo"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: demo-secret1
          objectType: secret        
          objectVersion: ""         
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"  
